# Generated by Django 2.2 on 2021-07-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amounts',
            field=models.CharField(default='', max_length=200),
        ),
    ]
