# Generated by Django 2.2 on 2021-07-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_address', serialize=False, to='user.User')),
                ('state', models.CharField(default='', max_length=20)),
                ('zip_code', models.IntegerField(default='')),
                ('city', models.CharField(default='', max_length=45)),
                ('line1', models.TextField(default='', max_length=100)),
                ('line2', models.TextField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
